### PR TITLE
Feature/download from sourceforge

### PR DESCRIPTION
**Pull request by AndreMiras**
Downloads DEB/RPM directly from Sourceforge

### CODE REVIEW

**Comment by kakawait** [comment]
The main issue I had, is that I was using that role on local playbook.. Thus without `cntlm` I can't get internet access, so to fetch `cntlm` from web will be blocking :)

I could be great to fallback on local filesystem if no internet

**Comment by AndreMiras** [comment]
OK I understand the idea and it makes sense.

**Comment by kakawait** [comment]
Or just give a switch using tag or something else. Because idea to get binary from internet is great if you're not using ansible on same local host :)

**Comment by AndreMiras** [comment]
Yes or we could go the other way around. e.g. use `cntlm_package_file` when it's set or use the online version if it's not set.
Just my days are very busy at the moment so I won't be able to do it this week I think.
Feel free to edit my PR or merge it and update later on.

**Comment by AndreMiras** [comment]
@kakawait I took a look at it and I think I'm almost there (for Debian at least).
Before going further I have a question. When you use:
```
{ role: ansible-cntlm, cntlm_package_file: files/cntlm-0.92.3-1.x86_64.rpm }
```
Is `cntlm_package_file` referring to a file on the host or on the remote?

**Comment by kakawait** [comment]
@AndreMiras Since I was using those role with local ansible, in my case host & remote were the same, so I never asked myself.

I will merge that version and I will upgrade after my vacancies.

**Comment by AndreMiras** [comment]
> @AndreMiras Since I was using those role with local ansible, in my case host & remote were the same, so I never asked myself.
OK, that's why.

> I will merge that version and I will upgrade after my vacancies.
Great thank you! Feel free to ping me when you do the changes so I can give it a try on Ubuntu.

**Pull request merged**
